general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Maple Mono NF ExtraLight", style = "Regular" }
bold = { family = "Maple Mono NF ExtraLight", style = "Bold" }
italic = { family = "Maple Mono NF ExtraLight" , style = "Italic" }
size = 11

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
